name: Testing

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        deno: ['v1.1.3', 'v1.2.0']
    name: Deno ${{ matrix.deno }} testing
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}
      - run: |
          deno test
