name: Testing

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        deno:
          - { version: v1.2.0, name: v1.2.0 }
          - { version: vx, name: latest }
    name: Deno ${{ matrix.deno.name }} testing
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno.version }}
      - run: |
          deno --version
          deno test
