# This is a basic workflow to help you get started with Actions

name: Testing

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        deno: ["v1.1.3", "v1.2.0", "", "v0.x"]
    name: Deno ${{ matrix.deno }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}
      - name: Run Tests
        run: |-
          deno --version
          deno tests
